name: make baipiao bot work
on:
  - issues
  - issue_comment

jobs:
  run-baipiao-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run the bot
        uses: docker://baipiaobot/baipiao-bot-rust:latest
        with:
          args: "${{ toJson(github) }}"
        env:
          BAIPIAO_BOT_TOKEN: ${{ secrets.BAIPIAO_BOT_TOKEN }}
