name: Build & Release

on: push
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . -t baipiao-bot-rust
          docker tag baipiao-bot-rust ${{ secrets.DOCKER_USERNAME }}/baipiao-bot-rust:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/baipiao-bot-rust
