name: Execute on everything
on:
  - issues
  - issue_comment

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Print
        run: |
          echo "${JSON}"
        env:
          JSON: ${{ toJson(github) }}
          BAIPIAO_BOT_TOKEN: ${{ secrets.BAIPIAO_BOT_TOKEN }}
